# Site
title:              Hauke Licht
position:           'Assistant Professor of Computational Political Science'
department:         'Department of Political Science and Digital Science Center'
university:         'University of Innsbruck'
# bio:                '<b>Assistant Professor of Computational Political Science</b><br/><em>University of Innsbruck</em>'
interests:          'computational social science, NLP, multilingual text analysis, political communication, and comparative politics'
description:        "Hi! I'm an Assistant Professor of Computational Political Science at the University of Innsbruck" 
reading_time:       false
# words_per_minute:   200
logo:               'assets/img/hauke_licht_front_color_narrow_small.jpg'
# background:         'assets/img/jack_vancet_ze_.jpg'
background:         'assets/img/bg_dark.jpg'
tiled_bg:           true   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://haukelicht.github.io
# url:                http://localhost:4000 

# Navigation
include-posts:      true
include-cv:         true
include-projects:   true
include-credits:    true

# Header
header_pages:
- about/index.md
- cv/index.md
- projects/index.md
- posts/index.md
- credits/index.md

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
# disqus_shortname:   

# Social
# if you don't have any of social below, comment the line.
# google:
#   plus:            #username
#   analytics:
#   verify:
#   ad-client:
#   ad-slot:
# bing-verify:
external-url:       https://www.uibk.ac.at/de/disc/team/
email:              hauke.licht@uibk.ac.at
# twitter:            hauke_licht
# facebook:           
github-url:         haukelicht
google-scholar:     GsY81VAAAAAJ
# stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:           hauke-licht-86854a349
# xing:              username
# instagram:          username
# lastfm:            username
# tumblr:            username
# medium:            '@username'
# pinterest:         username
# foursquare:        username
# steam:              username
# dribbble:          username
# youtube:           username
# youtube-channel:   channel
# soundcloud:        username
# weibo:             username
# flickr:            username
# codepen:           username
# keybase:           username
# xmpp:              username@server.com
# hackernews:        username

# Gems
plugins:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  # - jekyll-twitter-plugin

jekyll-mentions:
    base_url: https://github.com

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Exclude list
exclude: ['*.Rmd', README.md, notes.md, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
